print("akash")
print("there is lot of stuff's we need to do as a marketer")
A= ("Akash")
B= ("Andrayanallur")
print(A + B)
print("tamil nadu")
print("thiruppathi")
print("cuddalore")
print("There is lot of things i need to do")